name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/traffic-sign-classifier:latest .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/traffic-sign-classifier:latest

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: trafficsignclassifier-c9brh7a5a0gkcweu
        containerAppName: traffic-sign-classifier
        resourceGroup: traffic-sign-rg
        imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/traffic-sign-classifier:latest